#!/bin/bash

TARGET=""
CITY=""
START=""
DAYS=""
CMD="history"
DEATHS=0

printhelp () {

  cat <<EOF
Script to query nssav-ncov-sd csv data on covid-19 
usage:
$0
Commands:
list        - just output the raw csv for today
history     - show history for a specific country/state/city

Options:
-c|--city   - "Michigan"
-s|--start  - "2020-03-10"
--deaths    - show death numbers instead of case numbers
-d|--days 8 - number of days ago. Defaults to 8, (or 0 if listing the csv)
-h|--help   - print this help

EOF
}

listcsv() {
  DATE="$1"
  curl -k "https://nssac.bii.virginia.edu/covid-19/dashboard/data/nssac-ncov-sd-$DATE.csv" 2>/dev/null
}


while test $# -gt 0
do
  case "$1" in
    -c | --city)
      CITY="$2"
      shift 2
    ;;
    --deaths)
      DEATHS=1
      shift
    ;;
    -s | --start)
      START="$2"
      shift 2
    ;;
    -d | --days)
      DAYS="$2"
      shift 2
    ;;
    -h | --help)
      printhelp
      exit 0;
    ;;
    history)
       shift
    ;;
    list)
       shift;
       CMD="list"
    ;;
    *)
      if [ ! -z "$TARGET" ]; then >&2 echo "unknown arg $1"; exit 1; fi
      TARGET="$1"
      shift
    ;;
  esac
done

if [ -z "$TARGET" ]; then TARGET="Michigan"; fi

if [ ! -z "$START" ]; then
  DAYS="$((($(date +%s)-$(date +%s --date "$START"))/(3600*24)))"
else
  if [ -z "$DAYS" ]; then
    case $CMD in
      list) DAYS="0" ;;
      *) DAYS="8" ;;
    esac
  fi
  START="$(date -d "$date -$DAYS days" +%Y-%m-%d)"
fi

function history() {
  LAST=""
  >&2 echo "Querying covid-19 case counts for $TARGET $CITY after $START"
  for i in $(seq 1 $DAYS);
  do
    DATE="$(date -d "$START $i days" +%m-%d-%Y)";
    echo $DATE
    if [ ! -z "$CITY" ]
    then
      COUNT="$(listcsv $DATE | grep "$TARGET" | awk -F, '{ print $3}' | tr ';' '\n' | grep -F "$CITY" | awk '{ print $2 }')"
    else
      if [ "$DEATHS" -gt 0 ]; then PRINT='{ print $5 }'; else PRINT='{ print $4 }'; fi
      COUNT="$(listcsv $DATE | grep "$TARGET"| head -n 1 | awk -F, "$PRINT")"
    fi
    PLUS_MINUS=""
    if [ ! -z "$LAST" ]; then
      PLUS_MINUS="$((COUNT - LAST))"
      if [ "$PLUS_MINUS" -gt -1 ]; then
        PLUS_MINUS="+$PLUS_MINUS"
      fi

    fi
    LAST="$COUNT"
    echo "$COUNT" "$PLUS_MINUS"
  done;
}

function list() {
  listcsv $(date -d "$START" +%m-%d-%Y) | awk -F, '{print $1,$2,$4,$5,$6,$3}' OFS=, | column -s, -t | less -#2 -N -S
}

case "$CMD" in
  history) history ;;
  list) list ;;
esac
